### ISSUE TITLE
Preserve colours in the output of the program being watched

### ISSUE THREAD

**Issue by zeroviscosity** [unchartedsoftware/witch#2]

**Comment by kbirk** [comment]
Unfortunately I'm not exactly sure how to fix this.

The issue seems to be caused by wrapping the `Stdout` and `Stderr` properties of the `exec.Cmd` struct with a `io.Writer` implementation rather than directly assigning the `os.Stdout` `os.Stderr`:

```
c := exec.Command("/bin/sh", "-c", cmd)
c.Stdin = os.Stdin
c.Stdout = writer.NewCmd(os.Stdout)
c.Stderr = writer.NewCmd(os.Stderr)
```

instead of:

```
c := exec.Command("/bin/sh", "-c", cmd)
c.Stdin = os.Stdin
c.Stdout = os.Stdout
c.Stderr = os.Stderr
```

If the `cmd` executes a program that checks if `stdout` / `stderr` is a TTY before logging, it will return false. This can be confirmed quickly with:

```
c := exec.Command("/bin/sh", "-c", "if [ -t 1 ] ; then echo \"terminal\"; else echo \"not a terminal\"; fi")
```

I've spent a few hours tinkering and am currently at a loss of how to implement `io.Writer` in such a way that it preserves the `tty` status of `stdout` and `stderr`.

**Comment by kbirk** [comment]
Fixed!
